services:
  # PostgreSQL database container
  postgres:
    image: postgres:14-alpine # Use the official Postgres image
    environment:
      POSTGRES_PASSWORD: postgres # Replace with your desired password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres # Replace with your desired database name
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data
    ports:
      - '5432:5432'

# Define a volume to persist Postgres data
volumes:
  postgres_data: {}
